project:
  type: website
  output-dir: docs

website:
  title: "Richard Everitt's homepage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://scholar.google.com/citations?hl=en&user=UlZWgtsAAAAJ&view_op=list_works&sortby=pubdate
        text: Publications
      - href: https://richardgeveritt.github.io/ggsmc/
        text: ggsmc
      - href: https://github.com/richardgeveritt/RClonOr
        text: RClonOr

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



